# ==============================================================================
# Generated by qmake (2.01a) (Qt 4.5.2-tower) on: Mo. Aug 17 09:00:10 2009
# This file is generated by qmake and should not be modified by the
# user.
#  Name        : Makefile
#  Description : Wrapper Makefile for calling Symbian build tools
#
# ==============================================================================


QMAKE             = /home/gwd/Qt_S60/gnupoc/qt_s60/bin/qmake
DEL_FILE          = del
DEL_DIR           = rmdir
XCOPY             = xcopy /d /f /h /r /y /i
ABLD              = ABLD.BAT
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make

ifeq (WINS,$(findstring WINS, $(PLATFORM)))
ZDIR=$(EPOCROOT)epoc32\release\$(PLATFORM)\$(CFG)\Z
else
ZDIR=$(EPOCROOT)epoc32\data\z
endif

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -D_WCHAR_T_DECLARED -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
INCPATH	 =  -I"/home/gwd/Qt_S60/gnupoc/qt_s60/include/QtCore" -I"/home/gwd/Qt_S60/gnupoc/qt_s60/include/QtCore/tmp" -I"/home/gwd/Qt_S60/gnupoc/qt_s60/include/QtNetwork" -I"/home/gwd/Qt_S60/gnupoc/qt_s60/include/QtNetwork/tmp" -I"/home/gwd/Qt_S60/gnupoc/qt_s60/include/QtGui" -I"/home/gwd/Qt_S60/gnupoc/qt_s60/include/QtGui/tmp" -I"/home/gwd/Qt_S60/gnupoc/qt_s60/include" -I"/home/gwd/Qt_S60/gnupoc/qt_s60/include/tmp" -I"/home/gwd/Qt_S60/gnupoc/qt_s60/mkspecs/common/symbian" -I"/home/gwd/Qt_S60/gnupoc/qt_s60/mkspecs/common/symbian/tmp" -I"/home/gwd/Qt_S60/gnupoc/symbian-sdks/3.1/epoc32/include" -I"/home/gwd/src/svn/Calendar" -I"/home/gwd/src/svn/Calendar/tmp" -I"/home/gwd/Qt_S60/gnupoc/symbian-sdks/3.1/epoc32/include/stdapis" -I"/home/gwd/Qt_S60/gnupoc/symbian-sdks/3.1/epoc32/include/stdapis/sys" -I"/home/gwd/Qt_S60/gnupoc/symbian-sdks/3.1/epoc32/include/stdapis/stlport" -I"/home/gwd/Qt_S60/gnupoc/qt_s60/src/s60main" -I"/home/gwd/Qt_S60/gnupoc/qt_s60/src/s60main/tmp"
first: default
default: debug-winscw
all: debug release

qmake:
	$(QMAKE) -spec symbian-abld -o "bld.inf" "/home/gwd/src/svn/Calendar/FCalendar.pro"

bld.inf:
	$(QMAKE)

$(ABLD): bld.inf
	bldmake bldfiles

debug: $(ABLD)
	$(ABLD) build winscw udeb
	$(ABLD) build gcce udeb
	$(ABLD) build armv5 udeb
	$(ABLD) build armv6 udeb

release: $(ABLD)
	$(ABLD) build gcce urel
	$(ABLD) build armv5 urel
	$(ABLD) build armv6 urel

debug-winscw: $(ABLD)
	$(ABLD) build winscw udeb
debug-gcce: $(ABLD)
	$(ABLD) build gcce udeb
debug-armv5: $(ABLD)
	$(ABLD) build armv5 udeb
debug-armv6: $(ABLD)
	$(ABLD) build armv6 udeb
release-gcce: $(ABLD)
	$(ABLD) build gcce urel
release-armv5: $(ABLD)
	$(ABLD) build armv5 urel
release-armv6: $(ABLD)
	$(ABLD) build armv6 urel

export: $(ABLD)
	$(ABLD) export

cleanexport: $(ABLD)
	$(ABLD) cleanexport

/home/gwd/Qt_S60/gnupoc/qt_s60/bin/moc:
	(cd $(QTDIR)/src/tools/moc && $(MAKE))

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_calendar.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_calendar.cpp 2> NUL
moc_calendar.cpp: vcalparser.h \
		calendar.h \
		../../../Qt_S60/gnupoc/qt_s60/bin/moc
	/home/gwd/Qt_S60/gnupoc/qt_s60/bin/moc $(DEFINES) $(INCPATH) -DSYMBIAN calendar.h -o moc_calendar.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp 2> NUL
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

create_temps:
	-@ if test ! -e "/home/gwd/Qt_S60/gnupoc/qt_s60/include/QtCore/tmp"; then mkdir "/home/gwd/Qt_S60/gnupoc/qt_s60/include/QtCore/tmp"; fi
	-@ if test ! -e "/home/gwd/Qt_S60/gnupoc/qt_s60/include/QtCore/tmp/tmp"; then mkdir "/home/gwd/Qt_S60/gnupoc/qt_s60/include/QtCore/tmp/tmp"; fi
	-@ if test ! -e "/home/gwd/Qt_S60/gnupoc/qt_s60/include/QtNetwork/tmp"; then mkdir "/home/gwd/Qt_S60/gnupoc/qt_s60/include/QtNetwork/tmp"; fi
	-@ if test ! -e "/home/gwd/Qt_S60/gnupoc/qt_s60/include/QtNetwork/tmp/tmp"; then mkdir "/home/gwd/Qt_S60/gnupoc/qt_s60/include/QtNetwork/tmp/tmp"; fi
	-@ if test ! -e "/home/gwd/Qt_S60/gnupoc/qt_s60/include/QtGui/tmp"; then mkdir "/home/gwd/Qt_S60/gnupoc/qt_s60/include/QtGui/tmp"; fi
	-@ if test ! -e "/home/gwd/Qt_S60/gnupoc/qt_s60/include/QtGui/tmp/tmp"; then mkdir "/home/gwd/Qt_S60/gnupoc/qt_s60/include/QtGui/tmp/tmp"; fi
	-@ if test ! -e "/home/gwd/Qt_S60/gnupoc/qt_s60/include/tmp"; then mkdir "/home/gwd/Qt_S60/gnupoc/qt_s60/include/tmp"; fi
	-@ if test ! -e "/home/gwd/Qt_S60/gnupoc/qt_s60/include/tmp/tmp"; then mkdir "/home/gwd/Qt_S60/gnupoc/qt_s60/include/tmp/tmp"; fi
	-@ if test ! -e "/home/gwd/Qt_S60/gnupoc/qt_s60/mkspecs/common/symbian/tmp"; then mkdir "/home/gwd/Qt_S60/gnupoc/qt_s60/mkspecs/common/symbian/tmp"; fi
	-@ if test ! -e "/home/gwd/Qt_S60/gnupoc/qt_s60/mkspecs/common/symbian/tmp/tmp"; then mkdir "/home/gwd/Qt_S60/gnupoc/qt_s60/mkspecs/common/symbian/tmp/tmp"; fi
	-@ if test ! -e "/home/gwd/Qt_S60/gnupoc/symbian-sdks/3.1/epoc32/include/tmp"; then mkdir "/home/gwd/Qt_S60/gnupoc/symbian-sdks/3.1/epoc32/include/tmp"; fi
	-@ if test ! -e "/home/gwd/src/svn/Calendar/tmp"; then mkdir "/home/gwd/src/svn/Calendar/tmp"; fi
	-@ if test ! -e "/home/gwd/src/svn/Calendar/tmp/tmp"; then mkdir "/home/gwd/src/svn/Calendar/tmp/tmp"; fi
	-@ if test ! -e "/home/gwd/Qt_S60/gnupoc/symbian-sdks/3.1/epoc32/include/stdapis/tmp"; then mkdir "/home/gwd/Qt_S60/gnupoc/symbian-sdks/3.1/epoc32/include/stdapis/tmp"; fi
	-@ if test ! -e "/home/gwd/Qt_S60/gnupoc/symbian-sdks/3.1/epoc32/include/stdapis/sys/tmp"; then mkdir "/home/gwd/Qt_S60/gnupoc/symbian-sdks/3.1/epoc32/include/stdapis/sys/tmp"; fi
	-@ if test ! -e "/home/gwd/Qt_S60/gnupoc/symbian-sdks/3.1/epoc32/include/stdapis/stlport/tmp"; then mkdir "/home/gwd/Qt_S60/gnupoc/symbian-sdks/3.1/epoc32/include/stdapis/stlport/tmp"; fi
	-@ if test ! -e "/home/gwd/Qt_S60/gnupoc/qt_s60/src/s60main/tmp"; then mkdir "/home/gwd/Qt_S60/gnupoc/qt_s60/src/s60main/tmp"; fi
	-@ if test ! -e "/home/gwd/Qt_S60/gnupoc/qt_s60/src/s60main/tmp/tmp"; then mkdir "/home/gwd/Qt_S60/gnupoc/qt_s60/src/s60main/tmp/tmp"; fi

extension_clean: compiler_clean
	-if test -f /home/gwd/Qt_S60/gnupoc/qt_s60/include/QtCore/tmp; then rmdir  /S /Q  /home/gwd/Qt_S60/gnupoc/qt_s60/include/QtCore/tmp; fi
	-if test -f /home/gwd/Qt_S60/gnupoc/qt_s60/include/QtCore/tmp/tmp; then rmdir  /S /Q  /home/gwd/Qt_S60/gnupoc/qt_s60/include/QtCore/tmp/tmp; fi
	-if test -f /home/gwd/Qt_S60/gnupoc/qt_s60/include/QtNetwork/tmp; then rmdir  /S /Q  /home/gwd/Qt_S60/gnupoc/qt_s60/include/QtNetwork/tmp; fi
	-if test -f /home/gwd/Qt_S60/gnupoc/qt_s60/include/QtNetwork/tmp/tmp; then rmdir  /S /Q  /home/gwd/Qt_S60/gnupoc/qt_s60/include/QtNetwork/tmp/tmp; fi
	-if test -f /home/gwd/Qt_S60/gnupoc/qt_s60/include/QtGui/tmp; then rmdir  /S /Q  /home/gwd/Qt_S60/gnupoc/qt_s60/include/QtGui/tmp; fi
	-if test -f /home/gwd/Qt_S60/gnupoc/qt_s60/include/QtGui/tmp/tmp; then rmdir  /S /Q  /home/gwd/Qt_S60/gnupoc/qt_s60/include/QtGui/tmp/tmp; fi
	-if test -f /home/gwd/Qt_S60/gnupoc/qt_s60/include/tmp; then rmdir  /S /Q  /home/gwd/Qt_S60/gnupoc/qt_s60/include/tmp; fi
	-if test -f /home/gwd/Qt_S60/gnupoc/qt_s60/include/tmp/tmp; then rmdir  /S /Q  /home/gwd/Qt_S60/gnupoc/qt_s60/include/tmp/tmp; fi
	-if test -f /home/gwd/Qt_S60/gnupoc/qt_s60/mkspecs/common/symbian/tmp; then rmdir  /S /Q  /home/gwd/Qt_S60/gnupoc/qt_s60/mkspecs/common/symbian/tmp; fi
	-if test -f /home/gwd/Qt_S60/gnupoc/qt_s60/mkspecs/common/symbian/tmp/tmp; then rmdir  /S /Q  /home/gwd/Qt_S60/gnupoc/qt_s60/mkspecs/common/symbian/tmp/tmp; fi
	-if test -f /home/gwd/Qt_S60/gnupoc/symbian-sdks/3.1/epoc32/include/tmp; then rmdir  /S /Q  /home/gwd/Qt_S60/gnupoc/symbian-sdks/3.1/epoc32/include/tmp; fi
	-if test -f /home/gwd/src/svn/Calendar/tmp; then rmdir  /S /Q  /home/gwd/src/svn/Calendar/tmp; fi
	-if test -f /home/gwd/src/svn/Calendar/tmp/tmp; then rmdir  /S /Q  /home/gwd/src/svn/Calendar/tmp/tmp; fi
	-if test -f /home/gwd/Qt_S60/gnupoc/symbian-sdks/3.1/epoc32/include/stdapis/tmp; then rmdir  /S /Q  /home/gwd/Qt_S60/gnupoc/symbian-sdks/3.1/epoc32/include/stdapis/tmp; fi
	-if test -f /home/gwd/Qt_S60/gnupoc/symbian-sdks/3.1/epoc32/include/stdapis/sys/tmp; then rmdir  /S /Q  /home/gwd/Qt_S60/gnupoc/symbian-sdks/3.1/epoc32/include/stdapis/sys/tmp; fi
	-if test -f /home/gwd/Qt_S60/gnupoc/symbian-sdks/3.1/epoc32/include/stdapis/stlport/tmp; then rmdir  /S /Q  /home/gwd/Qt_S60/gnupoc/symbian-sdks/3.1/epoc32/include/stdapis/stlport/tmp; fi
	-if test -f /home/gwd/Qt_S60/gnupoc/qt_s60/src/s60main/tmp; then rmdir  /S /Q  /home/gwd/Qt_S60/gnupoc/qt_s60/src/s60main/tmp; fi
	-if test -f /home/gwd/Qt_S60/gnupoc/qt_s60/src/s60main/tmp/tmp; then rmdir  /S /Q  /home/gwd/Qt_S60/gnupoc/qt_s60/src/s60main/tmp/tmp; fi

pre_targetdeps: \
	generated_sources \
	all_source_deps

generated_sources: \
	moc_calendar.cpp

all_source_deps: \
	../../../Qt_S60/gnupoc/qt_s60/src/s60main/qts60maindocument.h \
	../../../Qt_S60/gnupoc/qt_s60/src/s60main/qts60mainapplication.h \
	../../../Qt_S60/gnupoc/qt_s60/src/s60main/qts60mainappui.h \
	../../../Qt_S60/gnupoc/qt_s60/src/s60main/qts60main_mcrt0.cpp \
	calendar.h \
	vcalparser.h \
	task.h \
	tevent.h \
	ttodo.h

finalize:

winscw_deployment:

winscw_deployment_clean:

dodistclean:
	-if test -f /home/gwd/src/svn/Calendar/FCalendar_gcce_udeb.pkg; then $(DEL_FILE)  /home/gwd/src/svn/Calendar/FCalendar_gcce_udeb.pkg; fi
	-if test -f /home/gwd/src/svn/Calendar/FCalendar_gcce_urel.pkg; then $(DEL_FILE)  /home/gwd/src/svn/Calendar/FCalendar_gcce_urel.pkg; fi
	-if test -f /home/gwd/src/svn/Calendar/FCalendar_armv5_udeb.pkg; then $(DEL_FILE)  /home/gwd/src/svn/Calendar/FCalendar_armv5_udeb.pkg; fi
	-if test -f /home/gwd/src/svn/Calendar/FCalendar_armv5_urel.pkg; then $(DEL_FILE)  /home/gwd/src/svn/Calendar/FCalendar_armv5_urel.pkg; fi
	-if test -f /home/gwd/src/svn/Calendar/FCalendar_armv6_udeb.pkg; then $(DEL_FILE)  /home/gwd/src/svn/Calendar/FCalendar_armv6_udeb.pkg; fi
	-if test -f /home/gwd/src/svn/Calendar/FCalendar_armv6_urel.pkg; then $(DEL_FILE)  /home/gwd/src/svn/Calendar/FCalendar_armv6_urel.pkg; fi
	-if test -f /home/gwd/src/svn/Calendar/Makefile; then $(DEL_FILE)  /home/gwd/src/svn/Calendar/Makefile; fi
	-if test -f /home/gwd/src/svn/Calendar/Makefile_0xEb032ae2.mk; then $(DEL_FILE)  /home/gwd/src/svn/Calendar/Makefile_0xEb032ae2.mk; fi
	-if test -f /home/gwd/src/svn/Calendar/FCalendar_0xEb032ae2.mmp; then $(DEL_FILE)  /home/gwd/src/svn/Calendar/FCalendar_0xEb032ae2.mmp; fi
	-if test -f /home/gwd/src/svn/Calendar/FCalendar_reg.rss; then $(DEL_FILE)  /home/gwd/src/svn/Calendar/FCalendar_reg.rss; fi
	-if test -f /home/gwd/src/svn/Calendar/FCalendar.rss; then $(DEL_FILE)  /home/gwd/src/svn/Calendar/FCalendar.rss; fi
	-if test -f /home/gwd/src/svn/Calendar/FCalendar.loc; then $(DEL_FILE)  /home/gwd/src/svn/Calendar/FCalendar.loc; fi
	-if test -f /home/gwd/src/svn/Calendar/bld.inf; then $(DEL_FILE)  /home/gwd/src/svn/Calendar/bld.inf; fi

distclean: clean dodistclean

clean: $(ABLD)
	-$(ABLD) reallyclean
	-bldmake clean

run:
	-call /home/gwd/Qt_S60/gnupoc/symbian-sdks/3.1/epoc32\release\winscw\udeb\FCalendar.exe

